backend/state/urls.py
from django.urls import path

from backend.state import views as v

app_name = 'state'


urlpatterns = [
    path('', v.state_list, name='state_list'),
    path('uf/', v.uf_list, name='uf_list'),
    path('result/', v.state_result, name='state_result'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('expense/', include('backend.expense.urls', namespace='expense')),
    path('bookstore/', include('backend.bookstore.urls', namespace='bookstore')),
    path('state/', include('backend.state.urls', namespace='state')),
    path('product/', include('backend.product.urls', namespace='product')),
    path('admin/', admin.site.urls),
]

backend/state/views.py
from django.shortcuts import render

from .states import states


def state_list(request):
    template_name = 'state/state_list.html'

    regions = (
        ('n', 'Norte'),
        ('ne', 'Nordeste'),
        ('s', 'Sul'),
        ('se', 'Sudeste'),
        ('co', 'Centro-Oeste'),
    )

    context = {'regions': regions}
    return render(request, template_name, context)


def get_states(region):
    return [state for state in states.get(region).items()]


def uf_list(request):
    template_name = 'state/hx/uf_hx.html'
    region = request.GET.get('region')

    ufs = {
        'n': get_states('Norte'),
        'ne': get_states('Nordeste'),
        's': get_states('Sul'),
        'se': get_states('Sudeste'),
        'co': get_states('Centro-Oeste'),
    }

    context = {'ufs': ufs[region]}
    return render(request, template_name, context)


def state_result(request):
    template_name = 'state/hx/state_hx.html'
    region = request.GET.get('region')

    ufs = {
        'n': get_states('Norte'),
        'ne': get_states('Nordeste'),
        's': get_states('Sul'),
        'se': get_states('Sudeste'),
        'co': get_states('Centro-Oeste'),
    }

    context = {'ufs': ufs[region]}
    return render(request, template_name, context)

backend/state/templates/state/state_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Regiões e Estados do Brasil</h1>
  <h2 style="color: #3465a4;">Filtro com dropdowns dependentes</h2>

  <div class="row">

    <div class="col">
      <label>Região</label>
      <select
        name="region"
        class="form-control"
        hx-get="{% url 'state:uf_list' %}"
        hx-target="#uf"
      >
        <option value="">-----</option>
        {% for region in regions %}
          <option value="{{ region.0 }}">{{ region.1 }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="col">
      <label>UF</label>
      <select
        id="uf"
        class="form-control"
      >
        <option value="">-----</option>
        <!-- O novo conteúdo será inserido aqui. -->
      </select>
    </div>

  </div>

  <hr>

  <h2 style="color: #3465a4;">Filtrando várias tabelas com um clique</h2>

  <div class="row">

    <div class="col">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Região</th>
          </tr>
        </thead>
        <tbody>
          {% for region in regions %}
            <tr
              hx-get="{% url 'state:state_result' %}?region={{region.0}}"
              hx-target="#states"
            >
              <td>
                <a>{{ region.1 }}</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th>Estados</th>
          </tr>
        </thead>
        <tbody id="states">
          <!-- O novo conteúdo será inserido aqui. -->
        </tbody>
      </table>
    </div>

  </div>
{% endblock content %}